language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
before_install: ant init-ivy -buildfile helper.xml
install:
  - ant install -buildfile install.xml
  - jdk_switcher use oraclejdk8
