language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
before_install: ant init-ivy -buildfile helper.xml
install:
  - ant install -buildfile install.xml
